export const newArrivalArray = [
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "1Lorem ipsum dolor sit amet",
    slug: "1lorem-ipsum-dolor-sit-amet",
    price: "1499.99",
    thumbnails: [
      "na-card-a1.jpg",
      "na-card-a2.jpg",
      "na-card-a1.jpg",
      "na-card-a2.jpg",
      "na-card-a1.jpg",
      "na-card-a2.jpg",
      "na-card-a1.jpg",
      "na-card-a2.jpg",
    ],
    sizes: [23, 26, 27, 29, 30],
    rating: 5,
  },
  {
    img1: "na-card-a2.jpg",
    img2: "na-card-a1.jpg",
    title: "3Lorem ipsum dolor sit amet",
    slug: "3lorem-ipsum-dolor-sit-amet",
    price: "142299.99",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [23, 26, 27, 29, 30],
    rating: 3,
  },
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "4Lorem ipsum dolor sit amet",
    slug: "4lorem-ipsum-dolor-sit-amet",
    price: "222.99",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [23, 26, 27, 29, 30],
    rating: 3,
  },
  {
    img1: "na-card-a2.jpg",
    img2: "na-card-a1.jpg",
    title: "9Lorem ipsum dolor sit amet",
    slug: "9lorem-ipsum-dolor-sit-amet",
    price: "4444.99",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [23, 26, 27, 29, 30],
    rating: 1,
  },
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "666Lorem ipsum dolor sit amet",
    slug: "666lorem-ipsum-dolor-sit-amet",
    price: "442323244.99",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [23, 26, 27, 29, 30],
    rating: 5,
  },
];
